apiVersion: v1
kind: ConfigMap
metadata:
  namespace: x5-lot37
  name: app-variables
data:
      ##
  SECRET_KEY: django-insecure-$$h@+%iv=y#0^y*576lbv^0)p43rnp^&t23==ba7*da_rxn=z=
  ## Параметры БД для lot37
  ENGINE: django.db.backends.postgresql
  DATABASE_URL: postgres-service
  DATABASE_NAME: lot37
  DATABASE_PORT: "5432"
  DB_HOST: postgres-service
  
  #env variables for the postgres component
  POSTGRES_DB: lot37

  # #env variables for the backend component
  DJANGO_ENV: development
  DEBUG: "1"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_ADMIN_USER: admin
  DJANGO_ADMIN_EMAIL: "admin@example.com"
  DATABASE: postgres



