apiVersion: v1
kind: Secret
metadata:
  namespace: x5-lot37 
  name: django-credentials
type: Opaque
data:
  DATABASE_PASSWORD: cG9zdGdyZXM=
  DATABASE_USER: cG9zdGdyZXM=

---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: x5-lot37
  name: django-postgres-migrations
spec:
  ttlSecondsAfterFinished: 90
  activeDeadlineSeconds: 60
  template:
    spec:
      imagePullSecrets:
      - name: myregistry
      containers:
      - name: django-job-container
        image: gitlab.artw.ru:5050/com_projects/tenders/2025/x5_group/lot37:backend-latest
        imagePullPolicy: Always
        command: ["python", "manage.py", "migrate"]
        envFrom:
          - secretRef:
              name: django-credentials
          - configMapRef:
              name: app-variables    
      restartPolicy: Never
  backoffLimit: 3

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: x5-lot37
  name: django-pvc
spec:
  storageClassName: yc-network-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 