# Generated by Django 4.1 on 2024-04-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationKind",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "активен"), ("blocked", "заблокирован")],
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип коммуникации",
                "verbose_name_plural": "Типы коммуникации",
            },
        ),
        migrations.CreateModel(
            name="CommunicationSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "активен"), ("blocked", "заблокирован")],
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип коммуникации",
                "verbose_name_plural": "Типы коммуникации",
            },
        ),
        migrations.CreateModel(
            name="FavoriteSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "communication_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favorites",
                        to="communications.communicationsource",
                        verbose_name="Канал коммуникации",
                    ),
                ),
                (
                    "communication_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favorites",
                        to="communications.communicationkind",
                        verbose_name="Тип коммуникации",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="favorites",
                        to="departments.department",
                        verbose_name="Подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предпочитаемый канал связи",
                "verbose_name_plural": "Предпочитаемые каналы связи",
            },
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("communication_date", models.DateTimeField(auto_now_add=True, verbose_name="Дата коммуникации")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "активен"), ("blocked", "заблокирован")],
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "communication_kind",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communications",
                        to="communications.communicationkind",
                        verbose_name="Тип коммуникации",
                    ),
                ),
                (
                    "communication_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communications",
                        to="communications.communicationsource",
                        verbose_name="Канал коммуникации",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communications",
                        to="users.customuser",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коммуникация",
                "verbose_name_plural": "Коммуникации",
            },
        ),
    ]
