# Generated by Django 4.1 on 2024-04-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communication",
            name="status",
            field=models.CharField(
                choices=[("send", "отправлено"), ("failed", "не отправлено")], max_length=30, verbose_name="Статус"
            ),
        ),
    ]
