# Generated by Django 4.1 on 2024-04-04 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_alter_departmentcommunication_department"),
        ("communications", "0003_communication_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communication",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="communications",
                to="departments.department",
                verbose_name="Департамент",
            ),
        ),
        migrations.AlterField(
            model_name="communication",
            name="status",
            field=models.CharField(
                choices=[("send", "отправлено"), ("failed", "не отправлено"), ("booked", "забронировано")],
                max_length=30,
                verbose_name="Статус",
            ),
        ),
    ]
