# Generated by Django 4.1 on 2024-04-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0004_communication_department_alter_communication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communication",
            name="status",
            field=models.CharField(
                choices=[("send", "отправлено"), ("failed", "не отправлено"), ("reserved", "забронировано")],
                max_length=30,
                verbose_name="Статус",
            ),
        ),
    ]
