# Generated by Django 4.2 on 2025-03-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0005_alter_communication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="communication",
            name="communication_status",
            field=models.CharField(
                choices=[
                    ("", "Нет статуса"),
                    ("delivered", "Доставлено"),
                    ("viewed", "Просмотрено"),
                ],
                default="",
                max_length=30,
                verbose_name="Статус коммуникации",
            ),
        ),
    ]
