# Generated by Django 4.2 on 2025-03-19 12:27

from common.constants import StatusChoices
from communications.models import CommunicationSource
from django.db import migrations, transaction

communication_source = (
    ("SMS", StatusChoices.ACTIVE.value),
    ("Messenger", StatusChoices.ACTIVE.value),
    ("Электронная почта", StatusChoices.ACTIVE.value),
    ("Push", StatusChoices.ACTIVE.value),
)


def upgrade(apps, schema_editor):
    sources = [CommunicationSource(name=name, status=status) for name, status in communication_source]
    with transaction.atomic():
        CommunicationSource.objects.bulk_create(sources)


def downgrade(apps, schema_editor):
    CommunicationSource.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0006_communication_communication_status"),
    ]

    operations = [
        migrations.RunPython(upgrade, downgrade),
    ]
