# Generated by Django 4.2 on 2025-03-19 12:36

from common.constants import StatusChoices
from communications.models import CommunicationKind
from django.db import migrations, transaction

communication_kinds = (
    ("Массовая коммуникация", StatusChoices.ACTIVE.value),
    ("Персональная коммуникация", StatusChoices.ACTIVE.value),
    ("Информационная", StatusChoices.ACTIVE.value),
    ("Опрос", StatusChoices.ACTIVE.value),
    ("Коммерческий опрос", StatusChoices.ACTIVE.value),
    ("Сервисная коммуникация", StatusChoices.ACTIVE.value),
)


def upgrade(apps, schema_editor):
    kinds = [CommunicationKind(name=name, status=status) for name, status in communication_kinds]
    with transaction.atomic():
        CommunicationKind.objects.bulk_create(kinds)


def downgrade(apps, schema_editor):
    CommunicationKind.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0007_dm_seed_communication_source"),
    ]

    operations = [
        migrations.RunPython(upgrade, downgrade),
    ]
