FROM node:18-alpine as frontend-builder
WORKDIR /front
COPY ./frontend/package.json ./frontend/yarn.lock ./
RUN yarn
COPY ./frontend ./
RUN yarn build

FROM nginx:latest as frontend 
WORKDIR /var/www/
COPY ./nginx.conf /etc/nginx/
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=frontend-builder /front/dist ./frontend/dist
CMD ["nginx", "-g", "daemon off;"]
