# Generated by Django 4.1 on 2024-04-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=70, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения",
            },
        ),
        migrations.CreateModel(
            name="DepartmentCommunication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("limit_per_unit", models.IntegerField(verbose_name="Количество коммуникаций за единицу времени")),
                ("unit", models.CharField(max_length=30, verbose_name="Единица времени")),
                ("units_count", models.IntegerField(verbose_name="Количество коммуникаций за единицу времени")),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="departments.department",
                        verbose_name="Подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило коммуникации",
                "verbose_name_plural": "Правила коммуникации",
            },
        ),
    ]
