# Generated by Django 4.1 on 2024-04-04 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentcommunication",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rules",
                to="departments.department",
                verbose_name="Подразделение",
            ),
        ),
    ]
