# Generated by Django 4.2 on 2025-03-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_alter_departmentcommunication_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentcommunication",
            name="units_count",
            field=models.IntegerField(verbose_name="Количество едениц времени"),
        ),
    ]
