# Generated by Django 4.1 on 2024-04-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=70, verbose_name="Имя")),
                ("surname", models.CharField(max_length=70, verbose_name="Фамилия")),
                ("phone", models.CharField(max_length=30, verbose_name="Номер телефона")),
                ("email", models.EmailField(max_length=254, verbose_name="Адрес электронной почты")),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="CustomUserCommunication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("blocked_from", models.DateTimeField(verbose_name="Дата блокировки")),
                ("blocked_to", models.DateTimeField(verbose_name="Дата окончания блокировки")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "активен"), ("blocked", "заблокирован")],
                        max_length=70,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_communications",
                        to="users.customuser",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "",
            },
        ),
    ]
