# Generated by Django 4.1 on 2024-04-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customusercommunication",
            options={
                "verbose_name": "Доступность для коммуникации",
                "verbose_name_plural": "Доступность для коммуникации",
            },
        ),
    ]
