# Generated by Django 4.2 on 2025-03-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customusercommunication_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusercommunication",
            name="blocked_from",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата блокировки"),
        ),
        migrations.AlterField(
            model_name="customusercommunication",
            name="blocked_to",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата окончания блокировки"),
        ),
    ]
